This notebook objective is to analyze the result from the previous script: 01_explore_location.py

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.colors as mcolors

/tmp/ipykernel_12513/544913360.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [2]:
 # Load the CSV
csv_filepath = "/home/alex/sshfs_mountpoints/verde/Documents/pocket_tool/results/04_combine_pockets_pdb/00_aligning/pocket_location.csv"
location_df = pd.read_csv(csv_filepath, sep=";")
location_df

# Load CSV containing the class per dynid
csv_filepath = "/home/alex/sshfs_mountpoints/verde/Documents/pocket_tool/results/04_combine_pockets_pdb/00_aligning/align.csv"
align_df = pd.read_csv(csv_filepath, sep=";")
dynid_class_df = align_df[["dynid", "class_name"]].drop_duplicates().set_index("dynid")

# Filter for class A only
location_df = location_df.join(dynid_class_df, on="dynid")
location_df = location_df[location_df["class_name"] == "Class A (Rhodopsin)"]
location_df

,dynid,trajid,pocketid,is_centered,z_location,tm_contacts,class_name
0,184,11714,7,True,ecl,NaN,Class A (Rhodopsin)
1,124,11193,0,False,above,tm7,Class A (Rhodopsin)
2,910,16517,3,False,below,tm2_tm3_tm5_tm6,Class A (Rhodopsin)
3,183,11706,3,False,below,tm2_tm6_tm7_h8,Class A (Rhodopsin)
4,51,10522,8,False,above,tm4_tm5,Class A (Rhodopsin)
...,...,...,...,...,...,...,...
19976,947,16772,9,False,above,NaN,Class A (Rhodopsin)
19979,736,15338,9,False,below,NaN,Class A (Rhodopsin)
19980,810,15839,3,False,above,tm2_tm3_tm5_tm6_tm7,Class A (Rhodopsin)
19981,987,17033,3,False,above,tm1_tm2_tm3_tm6_tm7,Class A (Rhodopsin)
19982,54,10546,14,False,above,tm7,Class A (Rhodopsin)

Where are the pockets located in the Z-axis? In the ICL region? ECL? In the TM region above or below the middle line?

In [3]:
location_df.groupby("z_location").size().reset_index(name='count').sort_values(by='z_location', ascending=True)

  z_location  count
0      above   7125
1      below   8050
2        ecl   1132
3        icl   1891

How many of the pockets are located in the core of the receptor?

In [36]:
location_df.groupby(["is_centered"]).size().reset_index(name='count').sort_values(by='is_centered', ascending=True)

   is_centered  count
0        False  14864
1         True   3334

In [40]:
df_mod = location_df.groupby(["is_centered", "z_location"]).size().reset_index(name='count').sort_values(by='is_centered', ascending=True)
df_mod['frequency'] = round(df_mod['count'] / df_mod['count'].sum() * 100, 2)
df_mod

   is_centered z_location  count  frequency
0        False      above   5693      31.28
1        False      below   7406      40.70
2        False        ecl    483       2.65
3        False        icl   1282       7.04
4         True      above   1432       7.87
5         True      below    644       3.54
6         True        ecl    649       3.57
7         True        icl    609       3.35

How many pockets did not have any contact with a TM helix?

In [6]:
# Check the rows that "tm_contacts" is equal to NaN.
location_df[location_df['tm_contacts'].isna()].groupby("z_location").size().reset_index(name='count').sort_values(by='z_location', ascending=True)

  z_location  count
0      above    389
1      below    434
2        ecl    421
3        icl    159

In the above region, in between which helices are pockets located?

In [22]:
df_mod = location_df[(location_df["is_centered"] == False) & (location_df["z_location"] == "above")]
df_mod = df_mod.groupby("tm_contacts").size().reset_index(name='count').sort_values(by='count', ascending=False)
df_mod['frequency'] = round(df_mod['count'] / df_mod['count'].sum() * 100, 1)

# Define the colormap from light pink to deep purple
cmap = mcolors.LinearSegmentedColormap.from_list("pink_purple", ["#ffe7f8", "#FF00FF"])

# Normalize frequencies so that 1 maps to the lowest color and max maps to the highest
norm = mcolors.Normalize(vmin=1, vmax=df_mod['frequency'].max())

# Apply the colormap to get hex colors
df_mod['color'] = df_mod['frequency'].apply(lambda x: mcolors.to_hex(cmap(norm(x))))
df_mod[df_mod['frequency'] >= 1]

                    tm_contacts  count  frequency    color
64                          tm7    530        9.9  #ff00ff
42                      tm3_tm4    457        8.5  #ff24fe
1                       tm1_tm2    369        6.9  #ff4efd
59                          tm5    330        6.1  #ff63fc
22                      tm2_tm3    299        5.6  #ff6ffc
21                          tm2    244        4.5  #ff8cfb
40                      tm2_tm7    232        4.3  #ff92fb
41                          tm3    224        4.2  #ff94fb
60                      tm5_tm6    220        4.1  #ff96fa
63                      tm6_tm7    216        4.0  #ff99fa
55                          tm4    215        4.0  #ff99fa
0                           tm1    211        3.9  #ff9cfa
56                      tm4_tm5    201        3.7  #ffa1fa
18                  tm1_tm2_tm7    196        3.6  #ffa4fa
62                          tm6    173        3.2  #ffaefa
43                  tm3_tm4_tm5    149        2.8  #ffb9f9
32          tm2_tm3_tm5_tm6_tm7    125        2.3  #ffc5f9
20                      tm1_tm7    120        2.2  #ffc8f9
26      tm2_tm3_tm4_tm5_tm6_tm7     98        1.8  #ffd2f9
35              tm2_tm3_tm6_tm7     72        1.3  #ffe0f8
48                      tm3_tm5     67        1.2  #ffe2f8
50              tm3_tm5_tm6_tm7     67        1.2  #ffe2f8
5   tm1_tm2_tm3_tm4_tm5_tm6_tm7     55        1.0  #ffe7f8
23                  tm2_tm3_tm4     54        1.0  #ffe7f8

In [26]:
# Print the accumulated frequency of the rows with less than 1% frequency
accumulated_frequency = df_mod[(df_mod['frequency'] < 1) | (df_mod['tm_contacts'].str.count('_') >= 3)]['frequency'].sum()
print(f"Accumulated frequency of rows with less than 1% frequency or 4 or more helices contact: {accumulated_frequency}%")

Accumulated frequency of rows with less than 1% frequency or 4 or more helices contact: 15.5%

What about the below region?

In [30]:
df_mod = location_df[(location_df["is_centered"] == False) & (location_df["z_location"] == "below")]
df_mod = df_mod.groupby("tm_contacts").size().reset_index(name='count').sort_values(by='count', ascending=False)
df_mod['frequency'] = round(df_mod['count'] / df_mod['count'].sum() * 100, 1)

# Define the colormap from light pink to deep purple
cmap = mcolors.LinearSegmentedColormap.from_list("pink_purple", ["#ffe7f8", "#FF00FF"])

# Normalize frequencies so that 1 maps to the lowest color and max maps to the highest
norm = mcolors.Normalize(vmin=1, vmax=9.9) # Adjust vmax to the maximum frequency in above region

# Apply the colormap to get hex colors
df_mod['color'] = df_mod['frequency'].apply(lambda x: mcolors.to_hex(cmap(norm(x))))

df_mod[df_mod['frequency'] >= 1]

    tm_contacts  count  frequency    color
67      tm3_tm5    476        6.8  #ff51fd
63          tm3    402        5.8  #ff6afc
39      tm2_tm3    401        5.8  #ff6afc
77          tm5    377        5.4  #ff75fb
81          tm6    362        5.2  #ff7afb
3       tm1_tm2    355        5.1  #ff7dfb
78      tm5_tm6    355        5.1  #ff7dfb
40  tm2_tm3_tm4    307        4.4  #ff8ffb
54      tm2_tm4    294        4.2  #ff94fb
76          tm4    281        4.0  #ff99fa
68  tm3_tm5_tm6    272        3.9  #ff9cfa
84   tm6_tm7_h8    268        3.8  #ff9ffa
64      tm3_tm4    264        3.8  #ff9ffa
83      tm6_tm7    233        3.3  #ffabfa
1           tm1    229        3.3  #ffabfa
35      tm1_tm7    223        3.2  #ffaefa
85          tm7    221        3.2  #ffaefa
37          tm2    195        2.8  #ffb9f9
86       tm7_h8    122        1.7  #ffd5f9
28  tm1_tm2_tm7    117        1.7  #ffd5f9
36   tm1_tm7_h8    107        1.5  #ffdaf8
2        tm1_h8     94        1.3  #ffe0f8
21  tm1_tm2_tm4     73        1.0  #ffe7f8
72      tm3_tm6     67        1.0  #ffe7f8

In [31]:
# Print the accumulated frequency of the rows with less than 1% frequency
accumulated_frequency = df_mod[(df_mod['frequency'] < 1) | (df_mod['tm_contacts'].str.count('_') >= 3)]['frequency'].sum()
print(f"Accumulated frequency of rows with less than 1% frequency or 4 or more helices contact: {accumulated_frequency}%")

Accumulated frequency of rows with less than 1% frequency or 4 or more helices contact: 12.200000000000001%