In [3]:
import pandas as pd

/tmp/ipykernel_14547/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [4]:
csv_path = "/home/alex/sshfs_mountpoints/verde/Documents/pocket_tool/src/08_novel_structure_analysis/rmsd_comparison_novel_pocket.csv"

In [5]:
df = pd.read_csv(csv_path)
df.head()

    state replicate  frame      rmsd
0  active     rep_1      0  2.924088
1  active     rep_1      1  3.155045
2  active     rep_1      2  2.834194
3  active     rep_1      3  2.786832
4  active     rep_1      4  2.844464

In [10]:
df.sort_values(by=['rmsd'], inplace=True, ascending=True)
df[0:50]

       state replicate  frame      rmsd
6167  active     rep_2   1167  2.484967
6381  active     rep_2   1381  2.524944
6339  active     rep_2   1339  2.557279
6010  active     rep_2   1010  2.592913
6304  active     rep_2   1304  2.596735
5176  active     rep_2    176  2.598051
137   active     rep_1    137  2.601832
6183  active     rep_2   1183  2.609956
6295  active     rep_2   1295  2.615894
6014  active     rep_2   1014  2.616744
5315  active     rep_2    315  2.616859
6244  active     rep_2   1244  2.616954
6283  active     rep_2   1283  2.620382
6316  active     rep_2   1316  2.624556
5370  active     rep_2    370  2.628068
6005  active     rep_2   1005  2.628974
5816  active     rep_2    816  2.629739
5831  active     rep_2    831  2.630598
6189  active     rep_2   1189  2.630845
6305  active     rep_2   1305  2.632475
5389  active     rep_2    389  2.632684
118   active     rep_1    118  2.634313
5382  active     rep_2    382  2.636875
6331  active     rep_2   1331  2.637136
6596  active     rep_2   1596  2.637172
5951  active     rep_2    951  2.637543
5378  active     rep_2    378  2.637822
6136  active     rep_2   1136  2.639958
6595  active     rep_2   1595  2.641840
6007  active     rep_2   1007  2.641921
5419  active     rep_2    419  2.642130
5228  active     rep_2    228  2.642961
6185  active     rep_2   1185  2.644902
5975  active     rep_2    975  2.645118
5852  active     rep_2    852  2.645318
6330  active     rep_2   1330  2.646797
5844  active     rep_2    844  2.647730
5971  active     rep_2    971  2.649064
6164  active     rep_2   1164  2.649299
5316  active     rep_2    316  2.650689
5375  active     rep_2    375  2.650883
6034  active     rep_2   1034  2.655399
6345  active     rep_2   1345  2.658776
6383  active     rep_2   1383  2.659304
5426  active     rep_2    426  2.661284
6307  active     rep_2   1307  2.661495
5318  active     rep_2    318  2.662876
5103  active     rep_2    103  2.664088
5490  active     rep_2    490  2.665861
5988  active     rep_2    988  2.667010