In [2]:
import pandas as pd

/tmp/ipykernel_9672/4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

In [3]:
csv_path = "/home/alex/sshfs_mountpoints/verde/Documents/pocket_tool/results/02_cryptic_pocket_detection/00_detecting_based_on_volume/output_250730/cryptic_pockets.csv"

In [4]:
df = pd.read_csv(csv_path, sep=";")
df

,dyn_id,traj_id,pocket_id,n_closed_start,n_max_open,perc_open,perc_closed,perc_inter
0,4,10140,0,0,289,100.000000,0.000000,0.000000
1,4,10140,10,0,82,64.013841,0.000000,35.986159
2,4,10140,11,289,0,0.000000,100.000000,0.000000
3,4,10140,12,289,0,0.000000,100.000000,0.000000
4,4,10140,13,289,0,0.000000,100.000000,0.000000
...,...,...,...,...,...,...,...,...
23768,1111,18511,5,0,481,100.000000,0.000000,0.000000
23769,1111,18511,6,0,455,96.673597,0.000000,3.326403
23770,1111,18511,7,0,481,100.000000,0.000000,0.000000
23771,1111,18511,8,0,21,23.492723,0.000000,76.507277
23772,1111,18511,9,13,99,50.935551,2.702703,46.361746

These are the cryptic pockets we find when we consider cryptic as closed for at least 10% of the simulation (50 ns) and open for the same amount of time

In [6]:
df_m = df.copy()
df_m = df_m[df_m["perc_open"] > 10]
df_m = df_m[df_m["perc_closed"] > 10]
df_m

,dyn_id,traj_id,pocket_id,n_closed_start,n_max_open,perc_open,perc_closed,perc_inter
22,6,10150,0,0,188,50.131234,30.183727,19.685039
23,6,10150,10,0,103,46.981627,41.994751,11.023622
27,6,10150,14,0,229,60.104987,37.795276,2.099738
28,6,10150,15,0,210,55.118110,39.895013,4.986877
30,6,10150,1,0,212,57.480315,38.845144,3.674541
...,...,...,...,...,...,...,...,...
23747,1111,18509,9,68,33,15.800416,44.906445,39.293139
23753,1111,18510,3,0,28,14.968815,64.864865,20.166320
23754,1111,18510,4,0,37,16.839917,10.810811,72.349272
23759,1111,18510,9,0,174,61.954262,11.434511,26.611227
23766,1111,18511,3,0,181,45.945946,12.058212,41.995842

If we also add the condition to start as open, we have fewer:

In [7]:
df_m = df.copy()
df_m = df_m[df_m["perc_open"] > 10]
df_m = df_m[df_m["perc_closed"] > 10]
df_m = df_m[df_m["n_closed_start"] > 1] # 5 ns
df_m

,dyn_id,traj_id,pocket_id,n_closed_start,n_max_open,perc_open,perc_closed,perc_inter
62,7,10166,8,2,53,29.281768,57.458564,13.259669
128,11,10187,0,34,85,26.403326,53.430353,20.166320
141,11,10187,4,4,31,13.721414,49.272349,37.006237
142,11,10187,5,64,102,29.106029,61.954262,8.939709
160,12,10193,9,224,27,17.879418,46.569647,35.550936
...,...,...,...,...,...,...,...,...
23710,1109,18493,4,2,61,46.985447,11.018711,41.995842
23713,1109,18493,7,7,194,69.022869,10.602911,20.374220
23719,1110,18501,5,102,72,26.819127,35.343035,37.837838
23723,1110,18502,3,8,64,20.166320,19.958420,59.875260
23747,1111,18509,9,68,33,15.800416,44.906445,39.293139